version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: pos_erp
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: