import type { Metadata } from 'next';
import { Geist_Mono, Inter } from 'next/font/google';

import './globals.css';

import { TooltipProvider } from '@/components/ui/tooltip';

const fontSans = Inter({
    variable: '--font-sans',
    subsets: ['latin'],
});

const fontMono = Geist_Mono({
    variable: '--font-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`dark ${fontSans.variable} ${fontMono.variable} h-full antialiased`}
        >
            <body className="flex min-h-full flex-col">
                <TooltipProvider>{children}</TooltipProvider>
            </body>
        </html>
    );
}
